spring.profiles.active: production

server:
  port: 8081
#  ssl:
#    protocol: "TLSv1.2"
#    key-store: "classpath:tomcat.keystore"
#    key-store-password: password
#    key-password: password

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  data:
    mongodb:
      uri: mongodb://localhost/files

eureka:
  instance:
#    nonSecurePortEnabled: false
#    securePortEnabled: true
#    securePort: 8081

    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

logging:
  level:
    proto.ms: 'DEBUG'
    com.netflix.discovery: 'OFF'


---

spring:
    profiles: production

#eureka:
#  instance:
#    nonSecurePortEnabled: false
#    securePortEnabled: true
#    securePort: 8081
##    nonSecurePort: 81
