server:
  port: 8081


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  main:
    show_banner: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

logging:
  level:
    proto.ms: 'DEBUG'
    com.netflix.discovery: 'OFF'

aws:
  access.key: ${AWS_ACCESS_KEY}
  secret.key: ${AWS_SECRET_KEY}
  s3:
    bucket: remotefilesvc
  dynamodb:
    endpoint: "dynamodb.us-west-2.amazonaws.com"
